# Generated by Django 5.2 on 2025-05-29 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dob', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='client_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
