# Generated by Django 5.2 on 2025-05-27 14:19

import dob.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dob', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainhosting',
            name='client_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=dob.models.CustomUser),
        ),
        migrations.AlterField(
            model_name='domainhosting',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name=dob.models.CustomUser),
        ),
        migrations.AlterField(
            model_name='domainhosting',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name=dob.models.CustomUser),
        ),
        migrations.AlterField(
            model_name='plan',
            name='client_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=dob.models.CustomUser),
        ),
        migrations.AlterField(
            model_name='plan',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name=dob.models.CustomUser),
        ),
        migrations.AlterField(
            model_name='plan',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name=dob.models.CustomUser),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='client_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=dob.models.CustomUser),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name=dob.models.CustomUser),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name=dob.models.CustomUser),
        ),
    ]
