# Generated by Django 5.2 on 2025-05-27 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dob', '0002_alter_domainhosting_client_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='email',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='plan',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plans', to=settings.AUTH_USER_MODEL),
        ),
    ]
