# Generated by Django 5.2 on 2025-05-29 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dob', '0002_alter_plan_client_name_alter_plan_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainhosting',
            name='hd_payment_status',
            field=models.CharField(choices=[('unavailable', 'Unavailable'), ('pending', 'Pending'), ('done', 'Done')], default='unavailable', max_length=15),
        ),
    ]
