# Generated by Django 5.2.1 on 2025-05-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dob', '0003_remove_customuser_is_email_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
