# Generated by Django 5.1 on 2025-05-16 11:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dob', '0004_customuser_is_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email_verification_uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True),
        ),
    ]
