# Generated by Django 5.2 on 2025-05-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dob', '0004_alter_domainhosting_hd_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainhosting',
            name='hd_payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('done', 'Done')], default='pending', max_length=15),
        ),
    ]
