# Generated by Django 5.2 on 2025-05-27 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dob', '0004_remove_plan_client_plan_client_name_plan_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='assigned_spoc',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'team_lead', 'teamlead_profile__is_spoc': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spoc_assigned_workspaces', to=settings.AUTH_USER_MODEL),
        ),
    ]
