# Generated by Django 5.2 on 2025-05-27 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dob', '0005_workspace_assigned_spoc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='assigned_spoc',
        ),
    ]
