# Generated by Django 5.2 on 2025-05-29 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dob', '0005_alter_domainhosting_hd_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domainhosting',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='domainhosting',
            name='email',
        ),
        migrations.RemoveField(
            model_name='domainhosting',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='email',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='domainhosting',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domain_hostings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plan',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans', to=settings.AUTH_USER_MODEL),
        ),
    ]
