# Generated by Django 5.2 on 2025-05-30 05:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dob', '0006_remove_domainhosting_client_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='email',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='workspace',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspace', to=settings.AUTH_USER_MODEL),
        ),
    ]
