# Generated by Django 5.1 on 2025-05-20 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dob', '0006_staffprofile_teamleadprofile_delete_spocprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamleadprofile',
            name='designation',
            field=models.CharField(default='teamlead', max_length=100),
        ),
        migrations.AlterField(
            model_name='teamleadprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_lead_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
