# Generated by Django 5.1 on 2025-05-21 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dob', '0007_alter_teamleadprofile_designation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountantprofile',
            name='certification',
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='team_lead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dob.teamleadprofile'),
        ),
        migrations.AlterField(
            model_name='accountantprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='designation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teamleadprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teamlead_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ManagerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.CharField(default='Null', max_length=100, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'manager'}, on_delete=django.db.models.deletion.CASCADE, related_name='manager_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='accountantprofile',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dob.managerprofile'),
        ),
        migrations.AddField(
            model_name='teamleadprofile',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dob.managerprofile'),
        ),
    ]
