# Generated by Django 5.2 on 2025-05-30 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dob', '0007_remove_workspace_client_name_remove_workspace_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='assign_spoc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
