# Generated by Django 5.2 on 2025-05-28 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dob', '0007_plan_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='assign_spoc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
