# Generated by Django 5.2 on 2025-05-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dob', '0008_workspace_assign_spoc'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainhosting',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('expired', 'Expired')], default='running', max_length=10),
        ),
    ]
