# Generated by Django 5.1 on 2025-05-21 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dob', '0008_remove_accountantprofile_certification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managerprofile',
            name='contact_number',
        ),
    ]
