# Generated by Django 5.1 on 2025-05-21 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dob', '0010_alter_managerprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='teamleadprofile',
            name='id',
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teamleadprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='teamlead_profile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
