# Generated by Django 5.1 on 2025-05-22 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dob', '0011_remove_staffprofile_id_remove_teamleadprofile_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='client',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='description',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='duration_days',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='name',
        ),
        migrations.AddField(
            model_name='plan',
            name='billing',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='features',
            field=models.JSONField(default={'no': 'features'}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Done', 'Done'), ('Failed', 'Failed')], default='Done', max_length=20),
        ),
        migrations.AddField(
            model_name='plan',
            name='title',
            field=models.CharField(default='checking', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='Accountant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DomainHosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('assigned_to', models.CharField(blank=True, max_length=100, null=True)),
                ('domain_name', models.CharField(blank=True, max_length=100, null=True)),
                ('domain_provider', models.CharField(blank=True, max_length=100, null=True)),
                ('domain_account', models.CharField(blank=True, max_length=100, null=True)),
                ('domain_expiry', models.DateField(blank=True, null=True)),
                ('hosting_provider', models.CharField(blank=True, max_length=100, null=True)),
                ('hosting_provider_name', models.CharField(blank=True, max_length=100, null=True)),
                ('hosting_expiry', models.DateField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_hostings', to='dob.plan')),
            ],
        ),
        migrations.CreateModel(
            name='PlanRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(null=True)),
                ('overridden_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_requests', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dob.plan')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dob.accountant')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to='dob.planrequest')),
            ],
        ),
        migrations.DeleteModel(
            name='ClientPlan',
        ),
        migrations.DeleteModel(
            name='Website',
        ),
    ]
