# Generated by Django 5.2.1 on 2025-05-23 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dob', '0012_remove_website_client_remove_plan_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
