# Generated by Django 5.1 on 2025-05-26 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dob', '0012_remove_website_client_remove_plan_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_visited',
            field=models.BooleanField(default=False),
        ),
    ]
