# Generated by Django 5.2.1 on 2025-05-23 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dob', '0013_paymentrequest_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentrequest',
            name='client',
        ),
    ]
