# Generated by Django 5.2.1 on 2025-05-23 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dob', '0014_remove_paymentrequest_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planrequest',
            name='reviewed_by',
        ),
        migrations.DeleteModel(
            name='Accountant',
        ),
    ]
