# Generated by Django 5.2.1 on 2025-05-23 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dob', '0015_remove_planrequest_reviewed_by_delete_accountant'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='client_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
