# Generated by Django 5.2.1 on 2025-05-23 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dob', '0016_plan_client_name_plan_email_plan_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='payment_is_approved',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
