# Generated by Django 5.2.1 on 2025-05-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dob', '0017_plan_payment_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='is_workspace_activated',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
