# Generated by Django 5.2.1 on 2025-05-24 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dob', '0018_plan_is_workspace_activated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Done', 'Done'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
    ]
