# Generated by Django 5.2.1 on 2025-05-24 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dob', '0021_alter_plan_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
