# Generated by Django 5.2.1 on 2025-05-24 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dob', '0022_alter_plan_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Done', 'Done'), ('Failed', 'Failed')], default='Done', max_length=20),
        ),
    ]
