# Generated by Django 5.2.1 on 2025-05-24 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dob', '0023_alter_plan_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workspace_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('assign_staff', models.CharField(max_length=100)),
                ('hd_maintenance', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workspace', to='dob.planrequest')),
            ],
        ),
    ]
