# Generated by Django 5.2.1 on 2025-05-24 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dob', '0024_workspace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='plan_request',
        ),
        migrations.AddField(
            model_name='workspace',
            name='client_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='is_workspace_activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workspace',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='assign_staff',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='hd_maintenance',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='workspace_name',
            field=models.CharField(max_length=255),
        ),
    ]
