# Generated by Django 5.1 on 2025-05-26 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dob', '0013_customuser_is_visited'),
        ('dob', '0025_remove_workspace_plan_request_workspace_client_name_and_more'),
    ]

    operations = [
    ]
